# Generated by Django 6.0.2 on 2026-02-20 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
                ('material_category', models.CharField(choices=[('', 'Choose category'), ('fabrics', 'Fabrics'), ('trims', 'Trims'), ('accessories', 'Accessories')], max_length=11)),
                ('material_quantity', models.PositiveIntegerField(default=0)),
                ('material_unit', models.CharField(blank=True, max_length=20)),
                ('material_unitprice', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
