# Generated by Django 6.0.2 on 2026-02-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawMaterials',
            new_name='RawMaterial',
        ),
    ]
