# Generated by Django 6.0.2 on 2026-02-21 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_rename_rawmaterials_rawmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('fabrics', 'Fabrics'), ('trims', 'Trims'), ('accessories', 'Accessories')], max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_category',
            field=models.CharField(choices=[('fabrics', 'Fabrics'), ('trims', 'Trims'), ('accessories', 'Accessories')], max_length=15),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_app.materialunit'),
        ),
    ]
