# Generated by Django 6.0.2 on 2026-02-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0004_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='employee_id',
        ),
    ]
