# Generated by Django 6.0.2 on 2026-03-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0005_rename_username_account_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('sets', 'Sets')], max_length=20)),
                ('product_collection', models.CharField(choices=[('summer', 'Summer'), ('resort', 'Resort'), ('holiday', 'Holiday'), ('spring', 'Spring'), ('fall', 'Fall')], max_length=20)),
            ],
        ),
    ]
