# Generated by Django 6.0.2 on 2026-03-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_role', models.CharField(choices=[('production_manager', 'Production Manager'), ('production_employee', 'Production Employee')], max_length=30)),
            ],
        ),
    ]
