# Generated by Django 6.0.3 on 2026-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0007_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
