# Generated by Django 6.0.3 on 2026-04-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0008_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
