# Generated by Django 6.0.2 on 2026-04-09 20:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0009_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_garment', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('fabric_length', models.FloatField(blank=True, null=True)),
                ('fabric_width', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='system_app.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_app.rawmaterial')),
            ],
            options={
                'unique_together': {('product', 'raw_material')},
            },
        ),
    ]
