# Generated by Django 6.0.3 on 2026-04-29 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='minimum_threshold',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
