# Generated by Django 6.0.3 on 2026-05-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0014_orderitem_product_name_orderitem_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='material_cost',
            field=models.FloatField(default=0),
        ),
    ]
