# Generated by Django 6.0.3 on 2026-05-03 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0015_orderitem_material_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_unitprice',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='minimum_threshold',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
